services:
    ikom.json.normalizer:
        class: 'Ikom\RequestBundle\Normalizer\JSONNormalizer'
        public: true

    ikom.request.client.json:
        class: 'Ikom\RequestBundle\Request\IkomRequest'
        public: true
        shared: false
        arguments: ['@ikom.json.normalizer', '@request_stack']